# ICD-O-3 2.6原發部位代碼對照表
SITE_GROUPS = {
    "C00": "LIP",
    "C01": "BASE OF TONGUE",
    "C02": "OTHER AND UNSPECIFIED PARTS OF TONGUE",
    "C03": "GUM",
    "C04": "FLOOR OF MOUTH",
    "C05": "PALATE",
    "C06": "OTHER AND UNSPECIFIED PARTS OF MOUTH",
    "C07": "PAROTID GLANID",
    "C08": "OTHER AND UNSPECIFIED MAJOR SALIVARY GLANDS",
    "C09": "TONSIL",
    "C10": "OROPHARYNX",
    "C11": "NASOPHARYNX",
    "C12": "PYRIFORM SINUS",
    "C13": "HYPOPHARYNX",
    "C14": "OTHER AND ILL-DEFINED SITES IN LIP, ORAL CAVITY AND PHARYNX",
    "C15": "ESOPHAGUS",
    "C16": "STOMACH",
    "C17": "SMALL INTESTINE",
    "C18": "COLON",
    "C19": "RECTOSIGMOID JUNCTION",
    "C20": "RECTUM",
    "C21": "ANUS AND ANAL CANAL",
    "C22": "LIVER AND INTRAHEPATIC BILE DUCTS",
    "C23": "GALLBLADDER",
    "C24": "OTHER AND UNSPECIFIED PARTS OF BILIARY TRACT",
    "C25": "PANCREAS",
    "C26": "OTHER AND ILL-DEFINED DIGESTIVE ORGANS",
    "C30": "NASAL CAVITY AND MIDDLE EAR",
    "C31": "ACCESSORY SINUSES",
    "C32": "LARYNX",
    "C33": "TRACHEA",
    "C34": "BRONCHUS AND LUNG",
    "C37": "THYMUS",
    "C38": "HEART, MEDIASTINUM, AND PLEURA",
    "C39": "OTHER AND ILL-DEFINED SITES WITHIN RESPIRATORY SYSTEM AMD INTRATHORACIC ORGANS",
    "C40": "BONES, JOINTS AND ARTICULAR CARTILAGE OF LIMBS",
    "C41": "BONES, JOINTS AND ARTICULAR CARTILAGE OF OTHER AND UNSPECIFIED SITES",
    "C42": "HEMATOPOIETIC AND RETICULOENDOTHELIAL SYSTEMS",
    "C44": "SKIN",
    "C47": "PERIPHERAL NERVES AND AUTONOMIC NERVOUS SYSTEM",
    "C48": "RETROPERITONEUM AND PERITONEUM",
    "C49": "CONNECTIVE, SUBCUTANEOUS AND OTHER SOFT TISSUES",
    "C50": "BREAST",
    "C51": "VULVA",
    "C52": "VAGINA",
    "C53": "CERVIX UTERI",
    "C54": "CORPUS UTERI",
    "C55": "UTERUS, NOS",
    "C56": "OVARY",
    "C57": "OTHER AN UNSPECIFIED FEMALE GENITAL ORGANS",
    "C58": "PLACENTA",
    "C60": "PENIS",
    "C61": "PROSTATE GLAND",
    "C62": "TESTIS",
    "C63": "OTHER AND UNSPECIFIED MALE GENITAL ORGANS",
    "C64": "KIDNEY",
    "C65": "RENAL PELVIS",
    "C66": "URETER",
    "C67": "BLADDER",
    "C68": "OTHER AND UNSPECIFIED URINARY ORGANS",
    "C69": "EYE AND ADNEXA",
    "C70": "MENINGES",
    "C71": "BRAIN",
    "C72": "SPINAL CORD, CRANIAL NERVES, AND OTHER PARTS OF CENTRAL NERVOUS SYSTEM",
    "C73": "THYROID GLAND",
    "C74": "ADRENAL GLAND",
    "C75": "OTHER ENDOCRINE GLANDS AND RELATED STRUCTURES",
    "C76": "OTHER AND ILL-DEFINED SITES",
    "C77": "LYMPH NODES",
    "C80": "UNKNOWN PRIMARY SITE"
}


SITE_DETAILS = {
    "C000": "External upper lip",
    "C001": "External lower lip",
    "C003": "External lip, NOS",
    "C004": "Mucosa of upper lip",
    "C005": "Mucosa of lower lip",
    "C006": "Mucosa of lip, NOS",
    "C008": "Commissure of lip",
    "C002": "Overlapping lesion of lip",
    "C009": "Lip, NOS",

    "C019": "Base of tongue, NOS",

    "C020": "Dorsal surface of tongue, NOS",
    "C021": "Border of tongue",
    "C022": "Ventral surface of tongue, NOS",
    "C023": "Anterior 2/3 of tongue, NOS",
    "C024": "Lingual tonsil",
    "C028": "Junctional zone of tongue/Overlapping lesion of tongue", #C028有兩個名字
    "C029": "Tongue, NOS",

    "C030": "Upper Gum",
    "C031": "Lower gum",
    "C038": "Overlapping lesion of gum",
    "C039": "Gum, NOS",

    "C040": "Anterior floor of mouth",
    "C041": "Lateral floor of mouth",
    "C048": "Overlapping lesion of floor of mouth",
    "C049": "Floor of mouth, NOS",

    "C050": "Hard palate",
    "C051": "Soft palate, NOS",
    "C052": "Uvula",
    "C058": "Overlapping lesion of palate",
    "C059": "Palate, NOS",

    "C060": "Cheeck mucosa",
    "C061": "Vestibule of mouth",
    "C062": "Retromolar area",
    "C068": "Overlapping lesion of other and unspecified parts of mouth",
    "C069": "Mouth, NOS",

    "C079": "Parotid gland",

    "C080": "Submandibular gland",
    "C081": "Sublingual gland",
    "C088": "Overlapping lesion of major salivary glands",
    "C089": "Major salivary gland, NOS",

    "C090": "Tonsillar fossa",
    "C091": "Tonsillar pillar",
    "C098": "Overlapping lesion of tonsil",
    "C099": "Tonsil, NOS",

    "C100": "Vallecula",
    "C101": "Anterior surface of epiglottis",
    "C102": "Lateral wall of oropharynx",
    "C103": "Posterior wall of oropharynx",
    "C104": "Branchial cleft",
    "C108": "Overlapping lesions of oropharynx",
    "C109": "Oropharynx, NOS",

    "C110": "Superior wall of nasopharynx",
    "C111": "Posterior wall of nasopharynx",
    "C112": "Lateral wall of nasopharynx",
    "C113": "Anterior wall of nasopharynx",
    "C118": "Overlapping lesion of nasopharynx",
    "C119": "Nasopharynx, NOS",

    "C129": "Pyriform sinus",

    "C130": "Postcricoid region",
    "C131": "Hypopharyngeal aspect of aryepiglottic fold",
    "C132": "Posterior wall of hypopharynx",
    "C138": "Overlapping lesion of hypopharynx",
    "C139": "Hypopharynx, NOS",

    "C140": "Pharynx, NOS",
    "C142": "Waldeyer ring",
    "C148": "Overlapping lesion of lip, oral cavity and pharynx",

    "C150": "Cervical esophagus",
    "C151": "Thoracic esophagus",
    "C152": "Abdominal esophagus",
    "C153": "Upper third of esophagus",
    "C154": "Middle third of esophagus",
    "C155": "Lower third of esophagus",
    "C158": "Overlapping lesion of esophagus",
    "C159": "Esophagus, NOS",

    "C160": "Cardia, NOS",
    "C161": "Fundus of stomach",
    "C162": "Body of stomach",
    "C163": "Gastric antrum",
    "C164": "Pylorus",
    "C165": "Lesser curvature of stomach, NOS",
    "C166": "Greater curvature of stomach, NOS",
    "C168": "Overlapping lesion of stomach",
    "C169": "Stomach, NOS",

    "C170": "Duodenum",
    "C171": "Jejunum",
    "C172": "Ileum",
    "C173": "Meckel diverticulum",
    "C178": "Overlapping lesion of small intestine",
    "C179": "Small intestine, NOS",

    "C180": "Cecum",
    "C181": "Appendix",
    "C182": "Ascending colon",
    "C183": "Hepatic flexure of colon",
    "C184": "Transverse colon",
    "C185": "Splenic flexure of colon",
    "C186": "Descending colon",
    "C187": "Sigmoid colon",
    "C188": "Overlapping lesion of colon",
    "C189": "Colon, NOS",

    "C199": "Rectosigmoid junction",

    "C209": "Rectum, NOS",
    
    "C210": "Anus, NOS",
    "C211": "Anal canal",
    "C212": "Cloacogenic zone",
    "C218": "Overlapping lesion of rectum, anus and anal canal",

    "C220": "Liver",
    "C221": "intrahepatic bile duct",

    "C239": "Gallbladder",

    "C240": "Extrahepatic bile duct",
    "C241": "Ampulla of Vater",
    "C248": "Overlapping lesion of billiary tract",
    "C249": "Billiary tract, NOS",

    "C250": "Head of pancreas",
    "C251": "Body of pancreas",
    "C252": "Tail of pancreas",
    "C253": "Pancreatic duct",
    "C254": "Islets of Langerhans",
    "C258": "Other specified parts of pancreas",
    "C257": "Overlapping lesion of pancreas",
    "C259": "Pancreas, NOS",

    "C260": "Intestinal tract, NOS",
    "C268": "Overlapping lesion of digestive system",
    "C269": "Gastrointestinal tract, NOS",

    "C300": "Nasal cavity",
    "C301": "Middle ear",

    "C310": "Maxillary sinus",
    "C311": "Ethmoid sinus",
    "C312": "Frontal sinus",
    "C313": "Sphenoid sinus",
    "C318": "Overlapping lesion of accessory sinuses",
    "C319": "Accessory sinus, NOS",

    "C320": "Glottis",
    "C321": "Supraglottis",
    "C322": "Subglottis",
    "C323": "Laryngeal cartilage",
    "C328": "Overlapping lesion of larynx",
    "C329": "Larynx, NOS",

    "C339": "Trachea",

    "C340": "Main bronchus",
    "C341": "Upper lobe, lung",
    "C342": "Middle lobe, lung",
    "C343": "Lower lobe, lung",
    "C348": "Overlapping lesion of lung",
    "C349": "Lung, NOS",

    "C379": "Thymus",

    "C380": "Heart",
    "C381": "Anterior mediastinum",
    "C382": "Posterior mediastinum",
    "C383": "Mediastinum, NOS",
    "C384": "Pleura, NOS",
    "C388": "Overlapping lesion of heart, mediastinum and pleura",

    "C390": "Upper respiratory tract, NOS",
    "C398": "Overlapping lesion of respiratory system and intrathoracic organs",
    "C399": "Ill-defined sites within respiratory system",

    "C400": "Long bones of upper limb, scapula and associated joints",
    "C401": "Short bones of upper limb and associated joints",
    "C402": "Long bones of lower limb and associated joints",
    "C403": "Short bones of lower limb and associated joints",
    "C408": "Overlapping lesion of bones, joints and articular cartilage of limbs",
    "C409": "Bone of limb, NOS",

    "C410": "Bones of skull and face and associated joints",
    "C411": "Mandible",
    "C412": "Vertebral column",
    "C413": "Rib, sternum, clavicle and associated joints",
    "C414": "Pelvic bones, sacrum, coccyx and associated joints",
    "C418": "Overlapping lesion of bones, joints and articular cartilage",
    "C419": "Bone, NOS",

    "C420": "Blood",
    "C421": "Bone marrow",
    "C422": "Spleen",
    "C423": "Reticuloendothelial system, NOS",
    "C424": "Hematopoietic system, NOS",

    "C440": "Skin of lip, NOS",
    "C441": "Eyelid",
    "C442": "External ear",
    "C443": "Skin of other and unspecified parts of face",
    "C444": "Skin of scalp and neck",
    "C445": "Skin of trunk",
    "C446": "Skin of upper limb and shoulder",
    "C447": "Skin of lower limb and hip",
    "C448": "Overlapping lesion of skin",
    "C449": "Skin, NOS",

    "C470": "Peripheral nerves and autonomic nervous system of head, face, and neck",
    "C471": "Peripheral nerves and autonomic nervous system of upper limb and shoulder",
    "C472": "Peripheral nerves and autonomic nervous system of lower limb and hip",
    "C473": "Peripheral nerves and autonomic nervous system of thorax",
    "C474": "Peripheral nerves and autonomic nervous system of abdomen",
    "C475": "Peripheral nerves and autonomic nervous system of pelvis",
    "C476": "Peripheral nerves and autonomic nervous system of trunk, NOS",
    "C478": "Overlapping lesion of peripheral nerves and autonomic nervous system",
    "C479": "Autonomic nervous system, NOS",

    "C480": "Retroperitoneum",
    "C481": "Specified parts of peritoneum",
    "C482": "Peritoneum, NOS",
    "C488": "Overlapping lesion of retroperitoneum and peritoneum",

    "C490": "Connective, Subcutaneous and other soft tissues of head, face, and neck",
    "C491": "Connective, Subcutaneous and other soft tissues of upper limb and shoulder",
    "C492": "Connective, Subcutaneous and other soft tissues of lower limb and hip",
    "C493": "Connective, Subcutaneous and other soft tissues of thorax",
    "C494": "Connective, Subcutaneous and other soft tissues of abdomen",
    "C495": "Connective, Subcutaneous and other soft tissues of pelvis",
    "C496": "Connective, Subcutaneous and other soft tissues of trunk, NOS",
    "C498": "Overlapping lesion of connective, subcutaneous and other soft tissues",
    "C499": "Connective, Subcutaneous and other soft tissues, NOS",

    "C500": "Nipple",
    "C501": "Central portion of breast",
    "C502": "Upper-inner quadrant of breast",
    "C503": "Lower-inner quadrant of breast",
    "C504": "Upper-outer quadrant of breast",
    "C505": "Lower-outer quadrant of breast",
    "C506": "Axillary tail of breast",
    "C508": "Overlapping lesion of breast",
    "C509": "Breast, NOS",

    "C510": "Labium majus",
    "C511": "Labium minus",
    "C512": "Clitorus",
    "C518": "Overlapping lesion of vulva",
    "C519": "Vulva, NOS",

    "C529": "Vagina, NOS",

    "C530": "Endocervix",
    "C531": "Exocervix",
    "C538": "Overlapping lesion of cervix uteri",
    "C539": "Cervix uteri",

    "C540": "Isthmus uteri",
    "C541": "Endometrium",
    "C542": "Myometrium",
    "C543": "Fundus uteri",
    "C548": "Overlapping lesion of corpus uteri",
    "C549": "Corpus uteri",

    "C559": "Uterus, NOS",

    "C569": "Ovary",

    "C570": "Fallopian tube",
    "C571": "Broad ligament",
    "C572": "Round ligament",
    "C573": "Parametrium",
    "C574": "Uterine adnexa",
    "C577": "Other specified parts of female genital organs",
    "C578": "Overlapping lesion of female genital organs",
    "C579": "Female genital tract, NOS",

    "C589": "Placenta",

    "C600": "Prepuce",
    "C601": "Glans penis",
    "C602": "Body of penis",
    "C608": "Overlapping lesion of penis",
    "C609": "Penis, NOS",

    "C619": "Prostate gland",

    "C620": "Undescended testis",
    "C621": "Descended testis",
    "C629": "Testis, NOS",

    "C630": "Epididymis",
    "C631": "Spermatic cord",
    "C632": "Scrotum, NOS",
    "C637": "Other specified parts of male genital organs",
    "C638": "Overlapping lesion of male genital organs",
    "C639": "Male genital organs, NOS",

    "C649": "Kidney, NOS",

    "C659": "Renal pelvis",

    "C669": "Ureter",

    "C670": "Trigone of bladder",
    "C671": "Dome of bladder",
    "C672": "Lateral wall of bladder",
    "C673": "Anterior wall of bladder",
    "C674": "Posterior wall of bladder",
    "C675": "Bladder neck",
    "C676": "Ureteric orifice",
    "C677": "Urachus",
    "C678": "Overlapping lesion of bladder",
    "C679": "Bladder, NOS",

    "C680": "Urethra",
    "C681": "Paraurethral gland",
    "C688": "Overlapping lesion of urinary organs",
    "C689": "Urinary system, NOS",

    "C690": "Conjunctiva",
    "C691": "Cornea, NOS",
    "C692": "Retina",
    "C693": "Choroid",
    "C694": "Ciliary body",
    "C695": "Lacrimal duct, NOS/Lacrimal gland", #C695有兩個名字
    "C696": "Orbit, NOS",
    "C698": "Overlapping lesion of eye and adnexa",
    "C699": "Eye, NOS",

    "C700": "Cerebral meninges",
    "C701": "Spinal meninges",
    "C709": "Meninges, NOS",

    "C710": "Cerebrum",
    "C711": "Frontal lobe",
    "C712": "Temporal lobe",
    "C713": "Parietal lobe",
    "C714": "Occipital lobe",
    "C715": "Ventricle, NOS",
    "C716": "Cerebellum, NOS",
    "C717": "Brain stem",
    "C718": "Overlapping lesion of brain",
    "C719": "Brain, NOS",

    "C720": "Spinal cord",
    "C721": "Cauda equina",
    "C722": "Olfactory nerve",
    "C723": "Optic nerve",
    "C724": "Acoustic nerve",
    "C725": "Cranial nerve, NOS",
    "C728": "Overlapping lesion of brain and central nervous system",
    "C729": "Nervous system, NOS",
    
    "C739": "Thyroid gland",

    "C740": "Cortex of adrenal gland",
    "C741": "Medulla of adrenal gland",
    "C749": "Adrenal gland, NOS",

    "C750": "Parathyroid gland",
    "C751": "Pituitary gland",
    "C752": "Craniopharyngeal duct",
    "C753": "Pineal gland",
    "C754": "Carotid body",
    "C755": "Aortic body and other paraganglia",
    "C758": "Overlapping lesion of endocrine glands and related structures",
    "C759": "Endocrine gland, NOS",

    "C760": "Head, face or neck, NOS",
    "C761": "Thorax, NOS",
    "C762": "Abdomen, NOS",
    "C763": "Pelvis, NOS",
    "C764": "Upper limb, NOS",
    "C765": "Lower limb, NOS",
    "C767": "Other ill-defined sites",
    "C768": "Overlapping lesion of ill-defined sites",

    "C770": "Lymph nodes of head, face and neck",
    "C771": "Intrathoracic lymph nodes",
    "C772": "Intra-abdominal lymph nodes",
    "C773": "Lymph nodes of axilla or arm",
    "C774": "Lymph nodes of inguinal region or leg",
    "C775": "Pelvic lymph nodes",
    "C778": "Lymph nodes of multiple regions",
    "C779": "Lymph node, NOS",

    "C809": "Unknown primary site"
}